#!/usr/bin/env python2

"""\
Create a web logos for sequences generated by the design pipeline.

Usage:
    pull_into_place make_web_logo <workspace> <round> <pdf_output>
    pull_into_place make_web_logo <directory> <pdf_output>

If you specify a workspace and a round number, the weblogo will be calculated 
for all the validated designs in that round.  If you specify a directory, the 
weblogo will just be calculated for the models in the given directory.

It would be nice to pass all unparsed options through to weblogo.  I'll have to 
think a bit about how to do that.
"""

from klab import docopt, scripting
from .. import pipeline, structures

import weblogolib as weblogo
import corebio

@scripting.catch_and_print_errors()
def main():
    args = docopt.docopt(__doc__)
    root = args['<workspace>']
    round = args['<round>']
    directory = args['<directory>']
    output_path = args['<pdf_output>']

    if directory:
        models = structures.load(directory)
        resfile = pipeline.load_resfile(directory)
        resis = sorted(int(i) for i in resfile.designable)
        print resis
        title = directory
        sequences = [
                ''.join(models['sequence'][i][j-1] for j in resis)
                for i in models.index
        ]

    else:
        workspace = pipeline.ValidatedDesigns(root, round)
        workspace.check_paths()
        title = workspace.focus_dir
        designs = [structures.Design(x) for x in workspace.output_subdirs]
        sequences = [x.resfile_sequence for x in designs]

    sequences = corebio.seq.SeqList(
            [corebio.seq.Seq(x) for x in sequences],
            alphabet=corebio.seq.unambiguous_protein_alphabet,
    )

    logo_data = weblogo.LogoData.from_seqs(sequences)
    logo_options = weblogo.LogoOptions()
    logo_options.title = title
    logo_format = weblogo.LogoFormat(logo_data, logo_options)

    with open(output_path, 'wb') as logo_file:
        document = weblogo.pdf_formatter(logo_data, logo_format)
        logo_file.write(document)

